//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpacerUnion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 500")]
        public global::System.Drawing.Point PartWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["PartWinLocation"]));
            }
            set {
                this["PartWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500, 500")]
        public global::System.Drawing.Point VobListWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["VobListWinLocation"]));
            }
            set {
                this["VobListWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500, 500")]
        public global::System.Drawing.Point InfoWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["InfoWinLocation"]));
            }
            set {
                this["InfoWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 150")]
        public global::System.Drawing.Point TreeWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["TreeWinLocation"]));
            }
            set {
                this["TreeWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500, 150")]
        public global::System.Drawing.Point PropWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["PropWinLocation"]));
            }
            set {
                this["PropWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500, 150")]
        public global::System.Drawing.Point SoundWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["SoundWinLocation"]));
            }
            set {
                this["SoundWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Language {
            get {
                return ((int)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWinShow {
            get {
                return ((bool)(this["InfoWinShow"]));
            }
            set {
                this["InfoWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TreeWinShow {
            get {
                return ((bool)(this["TreeWinShow"]));
            }
            set {
                this["TreeWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ObjectWinShow {
            get {
                return ((bool)(this["ObjectWinShow"]));
            }
            set {
                this["ObjectWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PropsWinShow {
            get {
                return ((bool)(this["PropsWinShow"]));
            }
            set {
                this["PropsWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VobListWinShow {
            get {
                return ((bool)(this["VobListWinShow"]));
            }
            set {
                this["VobListWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SoundWinShow {
            get {
                return ((bool)(this["SoundWinShow"]));
            }
            set {
                this["SoundWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ObjWinShowNext {
            get {
                return ((bool)(this["ObjWinShowNext"]));
            }
            set {
                this["ObjWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VobListWinShowNext {
            get {
                return ((bool)(this["VobListWinShowNext"]));
            }
            set {
                this["VobListWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PropWinShowNext {
            get {
                return ((bool)(this["PropWinShowNext"]));
            }
            set {
                this["PropWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfoWinShowNext {
            get {
                return ((bool)(this["InfoWinShowNext"]));
            }
            set {
                this["InfoWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TreeWinShowNext {
            get {
                return ((bool)(this["TreeWinShowNext"]));
            }
            set {
                this["TreeWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SoundWinShowNext {
            get {
                return ((bool)(this["SoundWinShowNext"]));
            }
            set {
                this["SoundWinShowNext"] = value;
            }
        }
    }
}
