//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpacerUnion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 300")]
        public global::System.Drawing.Point PartWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["PartWinLocation"]));
            }
            set {
                this["PartWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 300")]
        public global::System.Drawing.Point VobListWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["VobListWinLocation"]));
            }
            set {
                this["VobListWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 300")]
        public global::System.Drawing.Point InfoWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["InfoWinLocation"]));
            }
            set {
                this["InfoWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 300")]
        public global::System.Drawing.Point TreeWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["TreeWinLocation"]));
            }
            set {
                this["TreeWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 300")]
        public global::System.Drawing.Point PropWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["PropWinLocation"]));
            }
            set {
                this["PropWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 300")]
        public global::System.Drawing.Point SoundWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["SoundWinLocation"]));
            }
            set {
                this["SoundWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Language {
            get {
                return ((int)(this["Language"]));
            }
            set {
                this["Language"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InfoWinShow {
            get {
                return ((bool)(this["InfoWinShow"]));
            }
            set {
                this["InfoWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TreeWinShow {
            get {
                return ((bool)(this["TreeWinShow"]));
            }
            set {
                this["TreeWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ObjectWinShow {
            get {
                return ((bool)(this["ObjectWinShow"]));
            }
            set {
                this["ObjectWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PropsWinShow {
            get {
                return ((bool)(this["PropsWinShow"]));
            }
            set {
                this["PropsWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VobListWinShow {
            get {
                return ((bool)(this["VobListWinShow"]));
            }
            set {
                this["VobListWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SoundWinShow {
            get {
                return ((bool)(this["SoundWinShow"]));
            }
            set {
                this["SoundWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ObjWinShowNext {
            get {
                return ((bool)(this["ObjWinShowNext"]));
            }
            set {
                this["ObjWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VobListWinShowNext {
            get {
                return ((bool)(this["VobListWinShowNext"]));
            }
            set {
                this["VobListWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PropWinShowNext {
            get {
                return ((bool)(this["PropWinShowNext"]));
            }
            set {
                this["PropWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfoWinShowNext {
            get {
                return ((bool)(this["InfoWinShowNext"]));
            }
            set {
                this["InfoWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TreeWinShowNext {
            get {
                return ((bool)(this["TreeWinShowNext"]));
            }
            set {
                this["TreeWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SoundWinShowNext {
            get {
                return ((bool)(this["SoundWinShowNext"]));
            }
            set {
                this["SoundWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200, 620")]
        public global::System.Drawing.Size MainWindowSize {
            get {
                return ((global::System.Drawing.Size)(this["MainWindowSize"]));
            }
            set {
                this["MainWindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point MainWindowPos {
            get {
                return ((global::System.Drawing.Point)(this["MainWindowPos"]));
            }
            set {
                this["MainWindowPos"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MainWindowMaxState {
            get {
                return ((bool)(this["MainWindowMaxState"]));
            }
            set {
                this["MainWindowMaxState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("405, 492")]
        public global::System.Drawing.Size TreeWinSize {
            get {
                return ((global::System.Drawing.Size)(this["TreeWinSize"]));
            }
            set {
                this["TreeWinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("346, 529")]
        public global::System.Drawing.Size PropsWinSize {
            get {
                return ((global::System.Drawing.Size)(this["PropsWinSize"]));
            }
            set {
                this["PropsWinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("323, 373")]
        public global::System.Drawing.Size VobListSize {
            get {
                return ((global::System.Drawing.Size)(this["VobListSize"]));
            }
            set {
                this["VobListSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 300")]
        public global::System.Drawing.Point GrassWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["GrassWinLocation"]));
            }
            set {
                this["GrassWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GrassWinShow {
            get {
                return ((bool)(this["GrassWinShow"]));
            }
            set {
                this["GrassWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GrassWinShowNext {
            get {
                return ((bool)(this["GrassWinShowNext"]));
            }
            set {
                this["GrassWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif; 8pt")]
        public string PropWindowFont {
            get {
                return ((string)(this["PropWindowFont"]));
            }
            set {
                this["PropWindowFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MacrosWinShow {
            get {
                return ((bool)(this["MacrosWinShow"]));
            }
            set {
                this["MacrosWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MacrosWinShowNext {
            get {
                return ((bool)(this["MacrosWinShowNext"]));
            }
            set {
                this["MacrosWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point MacrosWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["MacrosWinLocation"]));
            }
            set {
                this["MacrosWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("365, 430")]
        public global::System.Drawing.Size InfoWinSize {
            get {
                return ((global::System.Drawing.Size)(this["InfoWinSize"]));
            }
            set {
                this["InfoWinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatFilterWinShow {
            get {
                return ((bool)(this["MatFilterWinShow"]));
            }
            set {
                this["MatFilterWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MatFilterWinShowNext {
            get {
                return ((bool)(this["MatFilterWinShowNext"]));
            }
            set {
                this["MatFilterWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point MatFilterWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["MatFilterWinLocation"]));
            }
            set {
                this["MatFilterWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif; 8pt")]
        public string MainFont {
            get {
                return ((string)(this["MainFont"]));
            }
            set {
                this["MainFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float IconsUIScale {
            get {
                return ((float)(this["IconsUIScale"]));
            }
            set {
                this["IconsUIScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500, 500")]
        public global::System.Drawing.Point PFXEditorLocation {
            get {
                return ((global::System.Drawing.Point)(this["PFXEditorLocation"]));
            }
            set {
                this["PFXEditorLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("420, 771")]
        public global::System.Drawing.Size PFXEditorSize {
            get {
                return ((global::System.Drawing.Size)(this["PFXEditorSize"]));
            }
            set {
                this["PFXEditorSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFXEditorShow {
            get {
                return ((bool)(this["PFXEditorShow"]));
            }
            set {
                this["PFXEditorShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PFXEditorShowNext {
            get {
                return ((bool)(this["PFXEditorShowNext"]));
            }
            set {
                this["PFXEditorShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("550, 550")]
        public global::System.Drawing.Point ErrorWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["ErrorWinLocation"]));
            }
            set {
                this["ErrorWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("980, 566")]
        public global::System.Drawing.Size ErrorWinSize {
            get {
                return ((global::System.Drawing.Size)(this["ErrorWinSize"]));
            }
            set {
                this["ErrorWinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ErrorWinShow {
            get {
                return ((bool)(this["ErrorWinShow"]));
            }
            set {
                this["ErrorWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ErrorWinShowNext {
            get {
                return ((bool)(this["ErrorWinShowNext"]));
            }
            set {
                this["ErrorWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500, 500")]
        public global::System.Drawing.Point VobCatalogWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["VobCatalogWinLocation"]));
            }
            set {
                this["VobCatalogWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("615, 337")]
        public global::System.Drawing.Size VobCatalogWinSize {
            get {
                return ((global::System.Drawing.Size)(this["VobCatalogWinSize"]));
            }
            set {
                this["VobCatalogWinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VobCatalogWinShow {
            get {
                return ((bool)(this["VobCatalogWinShow"]));
            }
            set {
                this["VobCatalogWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool VobCatalogWinShowNext {
            get {
                return ((bool)(this["VobCatalogWinShowNext"]));
            }
            set {
                this["VobCatalogWinShowNext"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000, 500")]
        public global::System.Drawing.Point UVWinLocation {
            get {
                return ((global::System.Drawing.Point)(this["UVWinLocation"]));
            }
            set {
                this["UVWinLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("702, 597")]
        public global::System.Drawing.Size UVWinSize {
            get {
                return ((global::System.Drawing.Size)(this["UVWinSize"]));
            }
            set {
                this["UVWinSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UVWinShow {
            get {
                return ((bool)(this["UVWinShow"]));
            }
            set {
                this["UVWinShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UVWinShowNext {
            get {
                return ((bool)(this["UVWinShowNext"]));
            }
            set {
                this["UVWinShowNext"] = value;
            }
        }
    }
}
